Forms
Chike1990/Dev-Blog pull request #6
Opened 2022-08-26 22:44 UTC by Chike1990

In this Milestone, I:
created a method called current_user in the ApplicationController to make current user data available to all controllers.
created forms to perform the following functions:
     creates a Post on behalf of the current_user;
     create a comment on behalf of the current_user;
     and allow Users to add likes to Posts.

2022-08-26 23:40 UTC, andersonlebon requested changes
## Hi @Chike1990 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 23:40 UTC, andersonlebon commented on app/controllers/likes_controller.rb
> +  end
- [ ] KIndly solve this error that occurs when a post is liked 
![image](https://user-images.githubusercontent.com/65068771/187003113-de6d2d98-ef17-4177-b0b4-e163dcd36e5a.png)

2022-08-26 23:40 UTC, andersonlebon commented on app/views/comments/new.html.erb
> +</div>
- [ ] Kindly make sure this error is solved when a comment is created, check the redirection when a comment is created.

![image](https://user-images.githubusercontent.com/65068771/187003187-ce51eb7f-995c-49a7-80a7-a34331397dad.png)

2022-08-27 02:33 UTC, danielufeli approved these changes
Hi @Chike1990 ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 15:49 UTC, merged